services:
  kafka:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - 9092:9092
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@broker:9093
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: cache
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    networks:
      - app_network

  postgres:
    image: postgres:16
    container_name: database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - APP_DB_USER=${APP_DB_USER}
      - APP_DB_PASSWORD=${APP_DB_PASSWORD}
      - APP_DB_NAME=${APP_DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init/role.sh:/docker-entrypoint-initdb.d/role.sh
    networks:
      - app_network

  #server:
  #  ...

networks:
  app_network:
    driver: bridge

volumes:
  pgdata:
  redis-data: