package domain

type PaymentValidateTestCase struct {
	name     string
	payment  Payment
	expected bool
	wantErr  bool
	errMsg   string
}

var paymentTestCases []PaymentValidateTestCase = []PaymentValidateTestCase{
	{
		name: "valid payment",
		payment: Payment{
			Transaction:  "txn_123",
			RequestID:    "req_123",
			Currency:     "USD",
			Provider:     "stripe",
			Amount:       1500,
			PaymentDt:    1633024800,
			Bank:         "chase",
			DeliveryCost: 500,
			GoodsTotal:   900,
			CustomFee:    100,
		},
		expected: true,
		wantErr:  false,
	},
	{
		name: "missing required field - transaction",
		payment: Payment{
			Transaction:  "",
			Currency:     "USD",
			Provider:     "stripe",
			Amount:       1500,
			PaymentDt:    1633024800,
			Bank:         "chase",
			DeliveryCost: 500,
			GoodsTotal:   900,
			CustomFee:    100,
		},
		expected: false,
		wantErr:  true,
		errMsg:   "required",
	},
	{
		name: "amount zero",
		payment: Payment{
			Transaction:  "txn_123",
			Currency:     "USD",
			Provider:     "stripe",
			Amount:       0,
			PaymentDt:    1633024800,
			Bank:         "chase",
			DeliveryCost: 500,
			GoodsTotal:   900,
			CustomFee:    100,
		},
		expected: false,
		wantErr:  true,
		errMsg:   "gt",
	},
	{
		name: "negative delivery cost",
		payment: Payment{
			Transaction:  "txn_123",
			Currency:     "USD",
			Provider:     "stripe",
			Amount:       1500,
			PaymentDt:    1633024800,
			Bank:         "chase",
			DeliveryCost: -100,
			GoodsTotal:   900,
			CustomFee:    100,
		},
		expected: false,
		wantErr:  true,
		errMsg:   "gte",
	},
	{
		name: "goods total zero",
		payment: Payment{
			Transaction:  "txn_123",
			Currency:     "USD",
			Provider:     "stripe",
			Amount:       1500,
			PaymentDt:    1633024800,
			Bank:         "chase",
			DeliveryCost: 500,
			GoodsTotal:   0,
			CustomFee:    100,
		},
		expected: false,
		wantErr:  true,
		errMsg:   "gt",
	},
	{
		name: "negative custom fee",
		payment: Payment{
			Transaction:  "txn_123",
			Currency:     "USD",
			Provider:     "stripe",
			Amount:       1500,
			PaymentDt:    1633024800,
			Bank:         "chase",
			DeliveryCost: 500,
			GoodsTotal:   900,
			CustomFee:    -50,
		},
		expected: false,
		wantErr:  true,
		errMsg:   "gte",
	},
	{
		name: "amount consistency error - sum mismatch",
		payment: Payment{
			Transaction:  "txn_123",
			Currency:     "USD",
			Provider:     "stripe",
			Amount:       2000,
			PaymentDt:    1633024800,
			Bank:         "chase",
			DeliveryCost: 500,
			GoodsTotal:   900,
			CustomFee:    100,
		},
		expected: false,
		wantErr:  true,
		errMsg:   "amount consistency error",
	},
	{
		name: "valid with zero custom fee",
		payment: Payment{
			Transaction:  "txn_123",
			Currency:     "USD",
			Provider:     "stripe",
			Amount:       1400,
			PaymentDt:    1633024800,
			Bank:         "chase",
			DeliveryCost: 500,
			GoodsTotal:   900,
			CustomFee:    0,
		},
		expected: true,
		wantErr:  false,
	},
	{
		name: "valid with zero delivery cost",
		payment: Payment{
			Transaction:  "txn_123",
			Currency:     "USD",
			Provider:     "stripe",
			Amount:       1000,
			PaymentDt:    1633024800,
			Bank:         "chase",
			DeliveryCost: 0,
			GoodsTotal:   900,
			CustomFee:    100,
		},
		expected: true,
		wantErr:  false,
	},
}
