package domain

type OrderItemValidateTestCase struct {
	name      string
	orderItem OrderItem
	expected  bool
	wantErr   bool
	errMsg    string
}

var orderItemRequiredValidateTestCases []OrderItemValidateTestCase = []OrderItemValidateTestCase{
	{
		name: "chrt id required",
		orderItem: OrderItem{
			ChrtID:      0,
			TrackNumber: "WBILMTESTTRACK",
			Price:       453,
			Rid:         "ab4219087a764ae0btest",
			Name:        "Mascaras",
			Sale:        30,
			Size:        "0",
			TotalPrice:  317,
			NmID:        2389212,
			Brand:       "Vivienne Sabo",
			Status:      202,
		},
		expected: false,
		wantErr:  true,
		errMsg:   "required",
	},
	{
		name: "Track number required",
		orderItem: OrderItem{
			ChrtID:      1,
			TrackNumber: "",
			Price:       453,
			Rid:         "ab4219087a764ae0btest",
			Name:        "Mascaras",
			Sale:        30,
			Size:        "0",
			TotalPrice:  317,
			NmID:        2389212,
			Brand:       "Vivienne Sabo",
			Status:      202,
		},
		expected: false,
		wantErr:  true,
		errMsg:   "required",
	},
	{
		name: "Price required",
		orderItem: OrderItem{
			ChrtID:      1,
			TrackNumber: "a",
			Price:       0,
			Rid:         "ab4219087a764ae0btest",
			Name:        "Mascaras",
			Sale:        30,
			Size:        "0",
			TotalPrice:  317,
			NmID:        2389212,
			Brand:       "Vivienne Sabo",
			Status:      202,
		},
		expected: false,
		wantErr:  true,
		errMsg:   "required",
	},
	{
		name: "Rid required",
		orderItem: OrderItem{
			ChrtID:      1,
			TrackNumber: "a",
			Price:       1,
			Rid:         "",
			Name:        "Mascaras",
			Sale:        30,
			Size:        "0",
			TotalPrice:  317,
			NmID:        2389212,
			Brand:       "Vivienne Sabo",
			Status:      202,
		},
		expected: false,
		wantErr:  true,
		errMsg:   "required",
	},
	{
		name: "Name required",
		orderItem: OrderItem{
			ChrtID:      1,
			TrackNumber: "a",
			Price:       1,
			Rid:         "1",
			Name:        "",
			Sale:        30,
			Size:        "0",
			TotalPrice:  317,
			NmID:        2389212,
			Brand:       "Vivienne Sabo",
			Status:      202,
		},
		expected: false,
		wantErr:  true,
		errMsg:   "required",
	},
	{
		name: "Sale required",
		orderItem: OrderItem{
			ChrtID:      1,
			TrackNumber: "a",
			Price:       1,
			Rid:         "1",
			Name:        "1",
			Sale:        0,
			Size:        "0",
			TotalPrice:  317,
			NmID:        2389212,
			Brand:       "Vivienne Sabo",
			Status:      202,
		},
		expected: false,
		wantErr:  true,
		errMsg:   "required",
	},
	{
		name: "Size required",
		orderItem: OrderItem{
			ChrtID:      1,
			TrackNumber: "a",
			Price:       1,
			Rid:         "1",
			Name:        "1",
			Sale:        1,
			Size:        "",
			TotalPrice:  317,
			NmID:        2389212,
			Brand:       "Vivienne Sabo",
			Status:      202,
		},
		expected: false,
		wantErr:  true,
		errMsg:   "required",
	},
	{
		name: "Total price required",
		orderItem: OrderItem{
			ChrtID:      1,
			TrackNumber: "a",
			Price:       1,
			Rid:         "1",
			Name:        "1",
			Sale:        1,
			Size:        "1",
			TotalPrice:  0,
			NmID:        2389212,
			Brand:       "Vivienne Sabo",
			Status:      202,
		},
		expected: false,
		wantErr:  true,
		errMsg:   "required",
	},
	{
		name: "NmID required",
		orderItem: OrderItem{
			ChrtID:      1,
			TrackNumber: "a",
			Price:       1,
			Rid:         "1",
			Name:        "1",
			Sale:        1,
			Size:        "1",
			TotalPrice:  1,
			NmID:        0,
			Brand:       "Vivienne Sabo",
			Status:      202,
		},
		expected: false,
		wantErr:  true,
		errMsg:   "required",
	},
	{
		name: "Brand required",
		orderItem: OrderItem{
			ChrtID:      1,
			TrackNumber: "a",
			Price:       1,
			Rid:         "1",
			Name:        "1",
			Sale:        1,
			Size:        "1",
			TotalPrice:  1,
			NmID:        1,
			Brand:       "",
			Status:      202,
		},
		expected: false,
		wantErr:  true,
		errMsg:   "required",
	},
	{
		name: "Status required",
		orderItem: OrderItem{
			ChrtID:      1,
			TrackNumber: "a",
			Price:       1,
			Rid:         "1",
			Name:        "1",
			Sale:        1,
			Size:        "1",
			TotalPrice:  1,
			NmID:        1,
			Brand:       "2",
			Status:      0,
		},
		expected: false,
		wantErr:  true,
		errMsg:   "required",
	},
}
