package domain

type DeliveryValidateTestCase struct {
	name     string
	delivery Delivery
	expected bool
	wantErr  bool
	errMsg   string
}

var deliveryRequiredValidateTestCases []DeliveryValidateTestCase = []DeliveryValidateTestCase{
	{
		name: "name required",
		delivery: Delivery{
			Name:    "",
			Phone:   "+9720000000",
			Zip:     "2639809",
			City:    "Kiryat Mozkin",
			Address: "Ploshad Mira 15",
			Region:  "Kraiot",
			Email:   "test@gmail.com",
		},
		expected: false,
		wantErr:  true,
		errMsg:   "required",
	},
	{
		name: "Phone required",
		delivery: Delivery{
			Name:    "Test Testov",
			Phone:   "",
			Zip:     "2639809",
			City:    "Kiryat Mozkin",
			Address: "Ploshad Mira 15",
			Region:  "Kraiot",
			Email:   "test@gmail.com",
		},
		expected: false,
		wantErr:  true,
		errMsg:   "required",
	},
	{
		name: "Zip required",
		delivery: Delivery{
			Name:    "Test Testov",
			Phone:   "+9720000000",
			Zip:     "",
			City:    "Kiryat Mozkin",
			Address: "Ploshad Mira 15",
			Region:  "Kraiot",
			Email:   "test@gmail.com",
		},
		expected: false,
		wantErr:  true,
		errMsg:   "required",
	},
	{
		name: "City required",
		delivery: Delivery{
			Name:    "Test Testov",
			Phone:   "+9720000000",
			Zip:     "2639809",
			City:    "",
			Address: "Ploshad Mira 15",
			Region:  "Kraiot",
			Email:   "test@gmail.com",
		},
		expected: false,
		wantErr:  true,
		errMsg:   "required",
	},
	{
		name: "Address required",
		delivery: Delivery{
			Name:    "Test Testov",
			Phone:   "+9720000000",
			Zip:     "2639809",
			City:    "Kiryat Mozkin",
			Address: "",
			Region:  "Kraiot",
			Email:   "test@gmail.com",
		},
		expected: false,
		wantErr:  true,
		errMsg:   "required",
	},
	{
		name: "Region required",
		delivery: Delivery{
			Name:    "Test Testov",
			Phone:   "+9720000000",
			Zip:     "2639809",
			City:    "Kiryat Mozkin",
			Address: "Ploshad Mira 15",
			Region:  "",
			Email:   "test@gmail.com",
		},
		expected: false,
		wantErr:  true,
		errMsg:   "required",
	},
	{
		name: "Email required",
		delivery: Delivery{
			Name:    "Test Testov",
			Phone:   "+9720000000",
			Zip:     "2639809",
			City:    "Kiryat Mozkin",
			Address: "Ploshad Mira 15",
			Region:  "Kraiot",
			Email:   "",
		},
		expected: false,
		wantErr:  true,
		errMsg:   "required",
	},
}

var deliveryPhoneValidateTestCases []DeliveryValidateTestCase = []DeliveryValidateTestCase{
	{
		name: "valid phone",
		delivery: Delivery{
			Name:    "Test",
			Phone:   "+9720000000",
			Zip:     "2639809",
			City:    "Kiryat Mozkin",
			Address: "Ploshad Mira 15",
			Region:  "Kraiot",
			Email:   "test@gmail.com",
		},
		expected: true,
		wantErr:  false,
	},
	{
		name: "valid phone without plus",
		delivery: Delivery{
			Name:    "Test",
			Phone:   "9720000000",
			Zip:     "2639809",
			City:    "Kiryat Mozkin",
			Address: "Ploshad Mira 15",
			Region:  "Kraiot",
			Email:   "test@gmail.com",
		},
		expected: true,
		wantErr:  false,
	},
	{
		name: "letters in phone",
		delivery: Delivery{
			Name:    "Test",
			Phone:   "abc1234567",
			Zip:     "2639809",
			City:    "Kiryat Mozkin",
			Address: "Ploshad Mira 15",
			Region:  "Kraiot",
			Email:   "test@gmail.com",
		},
		expected: false,
		wantErr:  true,
		errMsg:   "номер телефона имеет невалидный формат",
	},
	{
		name: "special symbols in phone",
		delivery: Delivery{
			Name:    "Test",
			Phone:   "123@456#7890",
			Zip:     "2639809",
			City:    "Kiryat Mozkin",
			Address: "Ploshad Mira 15",
			Region:  "Kraiot",
			Email:   "test@gmail.com",
		},
		expected: false,
		wantErr:  true,
		errMsg:   "номер телефона имеет невалидный формат",
	},
	{
		name: "brackets invalid",
		delivery: Delivery{
			Name:    "Test",
			Phone:   "+1 () 1234567890",
			Zip:     "2639809",
			City:    "Kiryat Mozkin",
			Address: "Ploshad Mira 15",
			Region:  "Kraiot",
			Email:   "test@gmail.com",
		},
		expected: false,
		wantErr:  true,
		errMsg:   "номер телефона имеет невалидный формат",
	},
	{
		name: "number of digits must be at least 10",
		delivery: Delivery{
			Name:    "Test",
			Phone:   "+1234",
			Zip:     "2639809",
			City:    "Kiryat Mozkin",
			Address: "Ploshad Mira 15",
			Region:  "Kraiot",
			Email:   "test@gmail.com",
		},
		expected: false,
		wantErr:  true,
		errMsg:   "номер телефона должен иметь как минимум 10 цифр",
	},
}

var deliveryEmailValidateTestCases []DeliveryValidateTestCase = []DeliveryValidateTestCase{
	{
		name: "valid email",
		delivery: Delivery{
			Name:    "Test",
			Phone:   "+9720000000",
			Zip:     "2639809",
			City:    "Kiryat Mozkin",
			Address: "Ploshad Mira 15",
			Region:  "Kraiot",
			Email:   "test@gmail.com",
		},
		expected: true,
		wantErr:  false,
	},
	{
		name: "without '@'",
		delivery: Delivery{
			Name:    "Test",
			Phone:   "+9720000000",
			Zip:     "2639809",
			City:    "Kiryat Mozkin",
			Address: "Ploshad Mira 15",
			Region:  "Kraiot",
			Email:   "testgmail.com",
		},
		expected: false,
		wantErr:  true,
		errMsg:   "email имеет невалидный формат",
	},
	{
		name: "without '@'",
		delivery: Delivery{
			Name:    "Test",
			Phone:   "+9720000000",
			Zip:     "2639809",
			City:    "Kiryat Mozkin",
			Address: "Ploshad Mira 15",
			Region:  "Kraiot",
			Email:   "testgmail.com",
		},
		expected: false,
		wantErr:  true,
		errMsg:   "email имеет невалидный формат",
	},
	{
		name: "more than one '@'",
		delivery: Delivery{
			Name:    "Test",
			Phone:   "+9720000000",
			Zip:     "2639809",
			City:    "Kiryat Mozkin",
			Address: "Ploshad Mira 15",
			Region:  "Kraiot",
			Email:   "test@gma@l.com",
		},
		expected: false,
		wantErr:  true,
		errMsg:   "email имеет невалидный формат",
	},
	{
		name: "without .com",
		delivery: Delivery{
			Name:    "Test",
			Phone:   "+9720000000",
			Zip:     "2639809",
			City:    "Kiryat Mozkin",
			Address: "Ploshad Mira 15",
			Region:  "Kraiot",
			Email:   "test@gmail",
		},
		expected: false,
		wantErr:  true,
		errMsg:   "email имеет невалидный формат",
	},
}
